server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: 86400000000

spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      host: localhost
      database: word
  session:
    store-type: mongodb
    timeout: 2592000