server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: 86400000000
spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: ${WORD_MONGO_URL}
  session:
    store-type: mongodb
    timeout: 2592000